---
title: Trampedia
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: 'A wiki for trampoline coaches.

'
baseurl:
url: https://trampedia.siteleaf.net
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
sass:
    sass_dir: _sass
    style: compressed
plugins:
- jekyll-feed
