---
title: Trampedia
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: 'A wiki for trampoline coaches.

'
baseurl: 
url: https://e-compton.github.io/trampedia/
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
